#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : log4cpp
Version  : 1.1.3
Release  : 1
URL      : https://sourceforge.net/projects/log4cpp/files/log4cpp-1.1.x%20%28new%29/log4cpp-1.1/log4cpp-1.1.3.tar.gz
Source0  : https://sourceforge.net/projects/log4cpp/files/log4cpp-1.1.x%20%28new%29/log4cpp-1.1/log4cpp-1.1.3.tar.gz
Summary  : C++ library for flexible logging, modeled after Log4j
Group    : Development/Tools
License  : LGPL-2.1
Requires: log4cpp-bin = %{version}-%{release}
Requires: log4cpp-lib = %{version}-%{release}
Requires: log4cpp-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : doxygen
BuildRequires : graphviz
Patch1: 0001-Build-fixes.patch

%description
see doc/html or the project website (http://log4cpp.sf.net/).

%package bin
Summary: bin components for the log4cpp package.
Group: Binaries
Requires: log4cpp-license = %{version}-%{release}

%description bin
bin components for the log4cpp package.


%package dev
Summary: dev components for the log4cpp package.
Group: Development
Requires: log4cpp-lib = %{version}-%{release}
Requires: log4cpp-bin = %{version}-%{release}
Provides: log4cpp-devel = %{version}-%{release}
Requires: log4cpp = %{version}-%{release}

%description dev
dev components for the log4cpp package.


%package doc
Summary: doc components for the log4cpp package.
Group: Documentation

%description doc
doc components for the log4cpp package.


%package lib
Summary: lib components for the log4cpp package.
Group: Libraries
Requires: log4cpp-license = %{version}-%{release}

%description lib
lib components for the log4cpp package.


%package license
Summary: license components for the log4cpp package.
Group: Default

%description license
license components for the log4cpp package.


%prep
%setup -q -n log4cpp
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1556911825
export LDFLAGS="${LDFLAGS} -fno-lto"
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1556911825
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/log4cpp
cp COPYING %{buildroot}/usr/share/package-licenses/log4cpp/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/log4cpp-config

%files dev
%defattr(-,root,root,-)
/usr/include/log4cpp/AbortAppender.hh
/usr/include/log4cpp/Appender.hh
/usr/include/log4cpp/AppenderSkeleton.hh
/usr/include/log4cpp/AppendersFactory.hh
/usr/include/log4cpp/BasicConfigurator.hh
/usr/include/log4cpp/BasicLayout.hh
/usr/include/log4cpp/BufferingAppender.hh
/usr/include/log4cpp/Category.hh
/usr/include/log4cpp/CategoryStream.hh
/usr/include/log4cpp/Configurator.hh
/usr/include/log4cpp/DailyRollingFileAppender.hh
/usr/include/log4cpp/Export.hh
/usr/include/log4cpp/FactoryParams.hh
/usr/include/log4cpp/FileAppender.hh
/usr/include/log4cpp/Filter.hh
/usr/include/log4cpp/FixedContextCategory.hh
/usr/include/log4cpp/HierarchyMaintainer.hh
/usr/include/log4cpp/IdsaAppender.hh
/usr/include/log4cpp/Layout.hh
/usr/include/log4cpp/LayoutAppender.hh
/usr/include/log4cpp/LayoutsFactory.hh
/usr/include/log4cpp/LevelEvaluator.hh
/usr/include/log4cpp/LoggingEvent.hh
/usr/include/log4cpp/Manipulator.hh
/usr/include/log4cpp/NDC.hh
/usr/include/log4cpp/NTEventLogAppender.hh
/usr/include/log4cpp/OstreamAppender.hh
/usr/include/log4cpp/PassThroughLayout.hh
/usr/include/log4cpp/PatternLayout.hh
/usr/include/log4cpp/Portability.hh
/usr/include/log4cpp/Priority.hh
/usr/include/log4cpp/PropertyConfigurator.hh
/usr/include/log4cpp/RemoteSyslogAppender.hh
/usr/include/log4cpp/RollingFileAppender.hh
/usr/include/log4cpp/SimpleConfigurator.hh
/usr/include/log4cpp/SimpleLayout.hh
/usr/include/log4cpp/StringQueueAppender.hh
/usr/include/log4cpp/SyslogAppender.hh
/usr/include/log4cpp/TimeStamp.hh
/usr/include/log4cpp/TriggeringEventEvaluator.hh
/usr/include/log4cpp/TriggeringEventEvaluatorFactory.hh
/usr/include/log4cpp/Win32DebugAppender.hh
/usr/include/log4cpp/config-MinGW32.h
/usr/include/log4cpp/config-openvms.h
/usr/include/log4cpp/config-win32.h
/usr/include/log4cpp/config.h
/usr/include/log4cpp/convenience.h
/usr/include/log4cpp/threading/BoostThreads.hh
/usr/include/log4cpp/threading/DummyThreads.hh
/usr/include/log4cpp/threading/MSThreads.hh
/usr/include/log4cpp/threading/OmniThreads.hh
/usr/include/log4cpp/threading/PThreads.hh
/usr/include/log4cpp/threading/Threading.hh
/usr/lib64/liblog4cpp.so
/usr/lib64/pkgconfig/log4cpp.pc
/usr/share/aclocal/*.m4
/usr/share/man/man3/log4cpp.3
/usr/share/man/man3/log4cpp::AbortAppender.3
/usr/share/man/man3/log4cpp::Appender.3
/usr/share/man/man3/log4cpp::Appender::AppenderMapStorage.3
/usr/share/man/man3/log4cpp::Appender::AppenderMapStorageInitializer.3
/usr/share/man/man3/log4cpp::AppenderSkeleton.3
/usr/share/man/man3/log4cpp::AppendersFactory.3
/usr/share/man/man3/log4cpp::BasicConfigurator.3
/usr/share/man/man3/log4cpp::BasicLayout.3
/usr/share/man/man3/log4cpp::BufferingAppender.3
/usr/share/man/man3/log4cpp::Category.3
/usr/share/man/man3/log4cpp::CategoryNameComponent.3
/usr/share/man/man3/log4cpp::CategoryStream.3
/usr/share/man/man3/log4cpp::ConfigureFailure.3
/usr/share/man/man3/log4cpp::DailyRollingFileAppender.3
/usr/share/man/man3/log4cpp::FactoryParams.3
/usr/share/man/man3/log4cpp::FileAppender.3
/usr/share/man/man3/log4cpp::Filter.3
/usr/share/man/man3/log4cpp::FixedContextCategory.3
/usr/share/man/man3/log4cpp::FormatModifierComponent.3
/usr/share/man/man3/log4cpp::HierarchyMaintainer.3
/usr/share/man/man3/log4cpp::IdsaAppender.3
/usr/share/man/man3/log4cpp::Layout.3
/usr/share/man/man3/log4cpp::LayoutAppender.3
/usr/share/man/man3/log4cpp::LayoutsFactory.3
/usr/share/man/man3/log4cpp::LevelEvaluator.3
/usr/share/man/man3/log4cpp::LoggingEvent.3
/usr/share/man/man3/log4cpp::MessageComponent.3
/usr/share/man/man3/log4cpp::MillisSinceEpochComponent.3
/usr/share/man/man3/log4cpp::NDC.3
/usr/share/man/man3/log4cpp::NDC::DiagnosticContext.3
/usr/share/man/man3/log4cpp::NDCComponent.3
/usr/share/man/man3/log4cpp::NTEventLogAppender.3
/usr/share/man/man3/log4cpp::OstreamAppender.3
/usr/share/man/man3/log4cpp::PassThroughLayout.3
/usr/share/man/man3/log4cpp::PatternLayout.3
/usr/share/man/man3/log4cpp::PatternLayout::PatternComponent.3
/usr/share/man/man3/log4cpp::Priority.3
/usr/share/man/man3/log4cpp::PriorityComponent.3
/usr/share/man/man3/log4cpp::ProcessorTimeComponent.3
/usr/share/man/man3/log4cpp::Properties.3
/usr/share/man/man3/log4cpp::PropertyConfigurator.3
/usr/share/man/man3/log4cpp::PropertyConfiguratorImpl.3
/usr/share/man/man3/log4cpp::RemoteSyslogAppender.3
/usr/share/man/man3/log4cpp::RollingFileAppender.3
/usr/share/man/man3/log4cpp::SecondsSinceEpochComponent.3
/usr/share/man/man3/log4cpp::SimpleConfigurator.3
/usr/share/man/man3/log4cpp::SimpleLayout.3
/usr/share/man/man3/log4cpp::StringLiteralComponent.3
/usr/share/man/man3/log4cpp::StringQueueAppender.3
/usr/share/man/man3/log4cpp::StringUtil.3
/usr/share/man/man3/log4cpp::SyslogAppender.3
/usr/share/man/man3/log4cpp::ThreadNameComponent.3
/usr/share/man/man3/log4cpp::TimeStamp.3
/usr/share/man/man3/log4cpp::TimeStampComponent.3
/usr/share/man/man3/log4cpp::TriggeringEventEvaluator.3
/usr/share/man/man3/log4cpp::TriggeringEventEvaluatorFactory.3
/usr/share/man/man3/log4cpp::Win32DebugAppender.3
/usr/share/man/man3/log4cpp::details.3
/usr/share/man/man3/log4cpp::details::base::validator::data.3
/usr/share/man/man3/log4cpp::details::optional::params::validator.3
/usr/share/man/man3/log4cpp::details::parameter::validator.3
/usr/share/man/man3/log4cpp::details::required::params::validator.3
/usr/share/man/man3/log4cpp::tab.3
/usr/share/man/man3/log4cpp::threading.3
/usr/share/man/man3/log4cpp::threading::MSMutex.3
/usr/share/man/man3/log4cpp::threading::MSScopedLock.3
/usr/share/man/man3/log4cpp::threading::Mutex.3
/usr/share/man/man3/log4cpp::threading::ScopedLock.3
/usr/share/man/man3/log4cpp::threading::ThreadLocalDataHolder.3
/usr/share/man/man3/log4cpp::width.3

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/log4cpp/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/liblog4cpp.so.5
/usr/lib64/liblog4cpp.so.5.0.6

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/log4cpp/COPYING
